# Generated by Django 2.1.5 on 2021-02-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('upbringing', models.TextField(default='Location of Upbringing: ', max_length=50)),
                ('certifications', models.CharField(max_length=200, null=True)),
                ('expertise', models.CharField(max_length=50, null='Area of Expertise: ')),
                ('email', models.EmailField(max_length=200, null=True)),
                ('available', models.TextField(default='Yes', max_length=50)),
            ],
        ),
    ]
