# Generated by Django 2.1.5 on 2021-02-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='available',
        ),
    ]
