# Generated by Django 2.1.5 on 2021-01-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='area',
            field=models.TextField(default='this is cool!'),
        ),
    ]
