# Generated by Django 2.1.5 on 2021-01-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentors_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='area',
            field=models.TextField(),
        ),
    ]
