# Generated by Django 2.1.5 on 2021-01-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_auto_20210103_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentors',
            old_name='description',
            new_name='upbringing',
        ),
    ]
