# Generated by Django 2.1.5 on 2021-01-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_auto_20210103_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='contact',
            field=models.TextField(default='Enter email address: '),
        ),
        migrations.AlterField(
            model_name='mentors',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
