# Generated by Django 2.1.5 on 2021-01-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_auto_20210103_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='contact',
            field=models.CharField(default='Enter email address: ', max_length=120),
        ),
    ]
