# Generated by Django 2.1.5 on 2021-01-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_auto_20210103_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='certifications',
            field=models.TextField(default='List your certifications here: '),
        ),
        migrations.AlterField(
            model_name='mentors',
            name='expertise',
            field=models.TextField(default='Areas of technical expertise: '),
        ),
        migrations.AlterField(
            model_name='mentors',
            name='upbringing',
            field=models.TextField(default='Location of iniial upbringing: '),
        ),
    ]
